version: "3.8"

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app/server
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev # Dockerfile для разработки
    ports:
      - "3000:5173"
    volumes:

      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=tru
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
